spring.application.name=resume-ai-backend
#spring.ai.ollama.chat.model=deepseek-r1:latest
spring.ai.openai.api-key=####
spring.datasource.url=jdbc:mysql://localhost:3306/resume_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.user.name=vinu
#spring.security.user.password=vinu
#spring.main.allow-bean-definition-overriding=true

spring.security.oauth2.client.registration.google.client-id=####
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173/generate-resume
# How Spring will send the client credentials (POST body instead of HTTP Basic)
#spring.security.oauth2.client.registration.google.client-authentication-method=post
#spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

# Optional ? override default provider endpoints (Spring has good defaults)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs


razorpay.key_id=####
razorpay.key_secret=####

